-- =====================================================
-- OSCU (Online Sales Control Unit) Refactor
-- Migrate from VSCU/Physical CU to OSCU REST API
-- Kenya Revenue Authority eTIMS System-to-System Integration
-- =====================================================

-- Add OSCU-specific fields to etims_config
ALTER TABLE etims_config
  ADD COLUMN IF NOT EXISTS oscu_device_id TEXT,
  ADD COLUMN IF NOT EXISTS oscu_serial_number TEXT,
  ADD COLUMN IF NOT EXISTS oscu_status TEXT DEFAULT 'inactive' CHECK (oscu_status IN ('active', 'inactive', 'pending'));

-- Add comment explaining deprecation
COMMENT ON COLUMN etims_config.cu_serial_number IS 'DEPRECATED: Use oscu_serial_number for OSCU (Online Sales Control Unit)';
COMMENT ON COLUMN etims_config.cu_status IS 'DEPRECATED: Use oscu_status for OSCU';
COMMENT ON COLUMN etims_config.cu_model IS 'DEPRECATED: Not needed for cloud-based OSCU';
COMMENT ON COLUMN etims_config.oscu_device_id IS 'OSCU device ID auto-generated by KRA API on initialization';
COMMENT ON COLUMN etims_config.oscu_serial_number IS 'OSCU serial number (csuSerialNo) from KRA response';
COMMENT ON COLUMN etims_config.oscu_status IS 'OSCU status: active, inactive, pending';

-- Add OSCU-specific fields to etims_invoices
ALTER TABLE etims_invoices
  ADD COLUMN IF NOT EXISTS qr_code_url TEXT,
  ADD COLUMN IF NOT EXISTS oscu_serial_number TEXT,
  ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'cash' CHECK (payment_method IN ('cash', 'card', 'mpesa', 'bank_transfer', 'credit')),
  ADD COLUMN IF NOT EXISTS notes TEXT;

COMMENT ON COLUMN etims_invoices.qr_code_url IS 'QR code URL (bCode) from KRA response for receipt display';
COMMENT ON COLUMN etims_invoices.oscu_serial_number IS 'OSCU serial number (csuSerialNo) from KRA at time of invoice submission';
COMMENT ON COLUMN etims_invoices.payment_method IS 'Payment method: cash, card, mpesa, bank_transfer, credit';
COMMENT ON COLUMN etims_invoices.notes IS 'Additional notes or remarks for the invoice';

-- Add OSCU-specific fields to etims_invoice_items
ALTER TABLE etims_invoice_items
  ADD COLUMN IF NOT EXISTS item_class_code TEXT,
  ADD COLUMN IF NOT EXISTS discount_rate DECIMAL(5, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10, 2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS barcode TEXT;

COMMENT ON COLUMN etims_invoice_items.item_class_code IS 'KRA product classification code (itemClsCd)';
COMMENT ON COLUMN etims_invoice_items.discount_rate IS 'Discount rate as percentage (0-100)';
COMMENT ON COLUMN etims_invoice_items.discount_amount IS 'Discount amount in currency';
COMMENT ON COLUMN etims_invoice_items.barcode IS 'Product barcode for KRA item tracking';

-- Create index for faster OSCU lookups
CREATE INDEX IF NOT EXISTS idx_etims_config_oscu_device_id ON etims_config(oscu_device_id);
CREATE INDEX IF NOT EXISTS idx_etims_invoices_oscu_serial ON etims_invoices(oscu_serial_number);
CREATE INDEX IF NOT EXISTS idx_etims_invoices_qr_code ON etims_invoices(qr_code_url);
CREATE INDEX IF NOT EXISTS idx_etims_invoice_items_class_code ON etims_invoice_items(item_class_code);

-- Update updated_at trigger for etims_config if not exists
CREATE OR REPLACE FUNCTION update_etims_config_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_etims_config_updated_at ON etims_config;
CREATE TRIGGER trigger_etims_config_updated_at
  BEFORE UPDATE ON etims_config
  FOR EACH ROW
  EXECUTE FUNCTION update_etims_config_updated_at();

-- Migration note
COMMENT ON TABLE etims_config IS 'eTIMS configuration using OSCU (Online Sales Control Unit) - cloud-based REST API integration, no physical device required';
